# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\adminpanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class aUi_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listearaci = QtWidgets.QListWidget(self.centralwidget)
        self.listearaci.setGeometry(QtCore.QRect(40, 50, 391, 421))
        self.listearaci.setObjectName("listearaci")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(560, 50, 160, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.goruntule_buton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.goruntule_buton.setObjectName("goruntule_buton")
        self.verticalLayout.addWidget(self.goruntule_buton)
        self.sil_buton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sil_buton.setObjectName("sil_buton")
        self.verticalLayout.addWidget(self.sil_buton)
        self.ekle_buton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ekle_buton.setObjectName("ekle_buton")
        self.verticalLayout.addWidget(self.ekle_buton)
        self.yasakla_buton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.yasakla_buton.setObjectName("yasakla_buton")
        self.verticalLayout.addWidget(self.yasakla_buton)
        self.sirala_buton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sirala_buton.setObjectName("sirala_buton")
        self.verticalLayout.addWidget(self.sirala_buton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.cikis_buton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cikis_buton.setObjectName("cikis_buton")
        self.verticalLayout.addWidget(self.cikis_buton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.goruntule_buton.setText(_translate("MainWindow", "ÜYE GÖRÜNTÜLE"))
        self.sil_buton.setText(_translate("MainWindow", "ÜYE SİL"))
        self.ekle_buton.setText(_translate("MainWindow", "ÜYE EKLE"))
        self.yasakla_buton.setText(_translate("MainWindow", "ÜYE YASAKLA"))
        self.sirala_buton.setText(_translate("MainWindow", "ÜYELERİ SIRALA"))
        self.cikis_buton.setText(_translate("MainWindow", "ÇIKIŞ YAP"))
